import type { Metadata } from "next";
import "./globals.css";
// Подключаем стандартные стили для правильного отображения карты Leaflet
import 'leaflet/dist/leaflet.css';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const systemFontFamily =
    'system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif';

  return (
    <html
      lang="en"
      className="h-full antialiased"
    >
      <body className="min-h-full flex flex-col" style={{ fontFamily: systemFontFamily }}>{children}</body>
    </html>
  );
}
